# 参考 http://www.tuicool.com/articles/veUjQba
# Web容器配置
server:
  port: 8080



spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.20.46:3306/46test?useUnicode=true&characterEncoding=UTF-8
    username: jyall
    password: jyall2015
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化连接个数
    initialSize: 1
    #最小连接个数
    minIdle: 1
    #最大连接个数
    maxActive: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 测试SQL语句
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    #监控端登录用户名密码
    loginUsername: admin
    loginPassword: jzli



