# Web容器配置
server:
  port: 7777
#是否开启swagger (true/false)
swagger:
  enable: true

spring:
  #热部署
  devtools:
      restart:
        enabled: true
  #Druid数据库配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jzli?useUnicode=true&autoReconnect=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化连接个数
    initialSize: 1
    #最小连接个数
    minIdle: 1
    #最大连接个数
    maxActive: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 测试SQL语句
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    #监控端登录用户名密码
    loginUsername: admin
    loginPassword: jzli
#redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    pool:
      max-idle: 300
      max-total: 1000
      max-wait: 1000
      testOnBorrow: true
      testOnReturn: true
      max-active: 1000


